### ISSUE TITLE
Different accelerators are used - '_' vs '&'

### ISSUE THREAD

**Issue by adem4ik** [mean00/avidemux2_i18n#38]
I'm not sure if it's fine or not, but it looks like translation files use different accelerators: from GTK and QT.

[Here](https://github.com/mean00/avidemux2_i18n/blob/5314805b0a0bc02796b256d648dcd9a6270e7025/avidemux_en.ts#L428C26-L428C26) is `_`.
`<source>Bitrate _Mode:</source>`

And [here](https://github.com/mean00/avidemux2_i18n/blob/5314805b0a0bc02796b256d648dcd9a6270e7025/avidemux_en.ts#L871) is `&`.
`<source>Stat&amp;us bar</source>`

You can close the issue, if it's not a bug.

**Comment by eumagga0x2a** [comment]
If I am not mistaken, underscore is used in translations of GUI elements implemented using Avidemux GUI toolkit while ampersand is used in GUI elements implemented directly in Qt.
